/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-02-03 19:51:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.forwards;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
response.setHeader("Pragma","no-cache");
  response.setHeader("Cache-Control","no-cache");
  response.setDateHeader("Expires",-1);

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\t\tadmin.onload();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\t<div id=\"adminPanel\">\n");
      out.write("\t\t<fieldset id=\"admin\">\n");
      out.write("\t\t\t<legend id=\"adminLegend\" class=\"ui-widget-header\">Administrative Functions:</legend>\t\n");
      out.write("\t\t\t<div id=\"holder\">\t\t\n");
      out.write("\t\t\t<div id=\"leftAdmin\">\n");
      out.write("\t\t\t<form id=\"adminForm\">\n");
      out.write("\t\t\t<label for=\"pricelist\">Upload Omas Price List:</label>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"file\" id=\"pricelistInput\"/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"submit\" id=\"pricelist\"/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<label for=\"invoice\">Upload Omas Invoice:</label>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"file\" id=\"invoiceInput\"/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"submit\" id=\"invoice\"/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<label for=\"url\">Scrape Omas Web Site:</label>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"text\" id=\"scrapeInput\" value = \"");
      out.print(request.getAttribute("defaultOmaUrl"));
      out.write("\"/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<input type=\"submit\" id=\"scrape\"/>\t\t\n");
      out.write("\t\t\t<input type=\"text\" id=\"command\"/>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"rightAdmin\">\n");
      out.write("\t\t\t<div id=\"adminTableDiv\" class=\"tableDiv\">\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t</div>\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t\t<!-- Dialog boxes -->\n");
      out.write("\t\t<div id=\"pricelistMissing\" class=\"dialog\">Please select price list to upload.</div>\t\t\t\t\n");
      out.write("\t\t<div id=\"invoiceMissing\" class=\"dialog\">Please select invoice to upload.</div>\t\t\t\t\n");
      out.write("\t\t<div id=\"scrapeMissing\" class=\"dialog\">Please enter web site to scrape.</div>\t\t\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
