/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-02-07 15:28:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.forwards;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jackiesdogs.bean.*;

public final class vendorSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
response.setHeader("Pragma","no-cache");
  response.setHeader("Cache-Control","no-cache");
  response.setDateHeader("Expires",-1);

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\t\tvendorSearch.onload();\n");
      out.write("\t\t");
 
			List<VendorOrder> vendorOrders = (List<VendorOrder>)request.getAttribute("orders");
			if (vendorOrders != null) {//we passed a list of vendorOrders to the page
				for (VendorOrder vendorOrder: vendorOrders) {		
      out.write("\n");
      out.write("\t\tvendorOrder.addItem(\"");
      out.print(vendorOrder.getId());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(vendorOrder.getOrderDateFormatted());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(vendorOrder.getDeliveryDateFormatted());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(vendorOrder.getTotalCost());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(vendorOrder.getStatus());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(vendorOrder.getVendor());
      out.write("\");\n");
      out.write("\t\t");

				}		
			}
		
      out.write("\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\t<div id=\"vendorSearchPanel\">\n");
      out.write("\t\t<fieldset id=\"vendorSearch\">\n");
      out.write("\t\t\t<legend id=\"vendorSearchLegend\" class=\"ui-widget-header\">Search Vendor Orders:</legend>\t\n");
      out.write("\t\t\t<div id=\"holder\">\t\t\n");
      out.write("\t\t\t<div id=\"leftVendorSearch\">\n");
      out.write("\t\t\t<form id=\"VendorOrderSearchForm\">\n");
      out.write("\t\t\t<label for=\"vendorStartDate\">Start Date:</label>\n");
      out.write("\t\t\t<input type=\"text\" id=\"vendorStartDate\" class=\"date\"/>\t\t\t\t\t\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<label for=\"vendorEndDate\">End Date:</label>\n");
      out.write("\t\t\t<input type=\"text\" id=\"vendorEndDate\" class=\"date\"/>\t\t\t\t\t\n");
      out.write("\t\t\t<br/>\t\t\t\n");
      out.write("\t\t\t<label for=\"vendorStatus\">Status (Hold down Ctl to make multiple selections):</label>\n");
      out.write("\t\t\t<select id=\"vendorStatus\">\n");
      out.write("\t\t\t");

				Set<String> statusKeys = VendorOrder.STATUS.keySet(); 
				   for (String key: statusKeys) { //iterate through statuses
			
      out.write("\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(VendorOrder.STATUS.get(key));
      out.write('"');
      out.write('>');
      out.print(VendorOrder.STATUS.get(key));
      out.write("</option>\t\t\t\n");
      out.write("\t\t\t");

			   }
			
      out.write("\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<label for=\"vendor\">Vendor (Hold down Ctl to make multiple selections):</label>\n");
      out.write("\t\t\t<select id=\"vendor\">\n");
      out.write("\t\t\t");

				List<String> vendorKeys = new ArrayList<String>(ProductGroup.VENDORS.keySet()); 
				for (int i=0; i<vendorKeys.size(); i++) { //iterate through vendors
			
      out.write("\n");
      out.write("\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(ProductGroup.VENDORS.get(vendorKeys.get(i)));
      out.write("</option>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<br/>\t\t\t\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"rightVendorSearch\">\n");
      out.write("\t\t\t<div id=\"vendorVendorSearchTableDiv\" class=\"tableDiv\">\n");
      out.write("\t\t\t<table id=\"vendorOrderDetails\" class=\"orderTable\">\n");
      out.write("\t\t    \t\t<tr>\n");
      out.write("\t\t    \t\t\t<th>ID</th>\n");
      out.write("\t        \t   \t\t<th>Customer Name</th>\n");
      out.write("\t\t    \t        <th>VendorOrder Date</th>\n");
      out.write("\t\t    \t        <th>Delivery Date</th>\n");
      out.write("\t\t    \t        <th>Total Price</th>\n");
      out.write("\t\t    \t        <th>VendorOrder Status</th>\t\t    \t        \n");
      out.write("\t\t\t        </tr>\n");
      out.write("\t\t\t</table>\t\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t</div>\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t</div>\t\t\t\t\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t\t<!-- Dialog boxes -->\n");
      out.write("\t\t<div id=\"confirmVendorOrderLoadDialog\" class=\"dialog\">Are you sure you wish to load this vendor order?</div>\t\t\t\t\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
