/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2012-12-30 15:48:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jackiesdogs.utility.*;
import java.text.SimpleDateFormat;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
response.setHeader("Pragma","no-cache");
  response.setHeader("Cache-Control","no-cache");
  response.setDateHeader("Expires",-1);

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t\torder.onload();\r\n");
      out.write("\t\t");
 
			Order order = (Order)request.getAttribute("order");
			if (order != null) {//we passed an existing order to the page
				Date deliveryDateTime = order.getDeliveryDateTime();
				String deliveryDate = new SimpleDateFormat("MM/d/yyyy", Locale.ENGLISH).format(deliveryDateTime); //convert date/time to date string
				String deliveryTime = new SimpleDateFormat("h:mm a", Locale.ENGLISH).format(deliveryDateTime); //convert date/time to time string
		
      out.write("\r\n");
      out.write("\t\torder.setValues(\"");
      out.print(order.getId());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(deliveryDate);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(deliveryTime);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getDiscount());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getCredit());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getDeliveryFee());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getTollExpense());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getTotalCost());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getPaymentMethod());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.getChangeDue());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.isDelivered());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(order.isPersonal());
      out.write("\");\r\n");
      out.write("\t\t");

				List<OrderItem> orderItems = order.getOrderItems();
				Customer customer = order.getCustomer();
		
      out.write("\r\n");
      out.write("\t\torder.populateCustomer({firstName:\"");
      out.print(customer.getFirstName());
      out.write("\",lastName:\"");
      out.print(customer.getLastName());
      out.write("\",streetAddress:\"");
      out.print(customer.getStreetAddress());
      out.write("\",aptAddress:\"");
      out.print(customer.getAptAddress());
      out.write("\",city:\"");
      out.print(customer.getCity());
      out.write("\",state:\"");
      out.print(customer.getState());
      out.write("\",zip:\"");
      out.print(customer.getZip());
      out.write("\",phone:\"");
      out.print(customer.getPhone());
      out.write("\",email:\"");
      out.print(customer.getEmail());
      out.write("\",custId:\"");
      out.print(customer.getId());
      out.write("\"});\r\n");
      out.write("\t\torder.populateCustomerDiv();\r\n");
      out.write("\t\t");

				OrderItem orderItem;
				Product product;

				for (int i=0; i<orderItems.size(); i++) {
					orderItem = orderItems.get(i);				
					product = orderItem.getProduct();
		
      out.write("\r\n");
      out.write("\t\torder.addItem(\"");
      out.print(orderItem.getId());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(orderItem.getQuantity());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(orderItem.getWeight());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getId());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getProductName());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getPrice());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getBillBy());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getEstimatedWeight());
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(product.getDescription());
      out.write("\");\r\n");
      out.write("\t\t");

				}
			}
		
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\t<div id=\"orderPanel\">\r\n");
      out.write("\t\t<fieldset id=\"details\">\r\n");
      out.write("\t\t\t<div id=\"holderOrder\" class=\"holder\">\t\t\r\n");
      out.write("\t\t\t<div id=\"leftOrder\">\r\n");
      out.write("\t\t\t<legend id=\"orderLegend\" class=\"ui-widget-header\">Enter Information:</legend>\t\r\n");
      out.write("\t\t\t<label for=\"customerLookup\">Lookup Customer: </label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"customerLookup\"/>\r\n");
      out.write("\t\t\t<div id=\"selectedCustomerDiv\"></div>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"editCustomerButton\"/>\r\n");
      out.write("\t\t\t<hr/>\t\r\n");
      out.write("\t\t\t<label for=\"quantity\">Item Quantity:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"quantity\" class=\"onlyNumbers item\"/>\r\n");
      out.write("\t\t\t<label for=\"quantityAvailable\">Quantity Available:</label> \t\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"quantityAvailable\" class=\"readOnly item\"/>\r\n");
      out.write("\t\t\t<br/>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<label for=\"item\">Select Item:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"item\" class=\"item\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"itemId\" class=\"hidden item\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"billBy\" class=\"hidden item\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"estimatedWeight\" class=\"hidden item\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"description\" class=\"hidden item\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"price\" class=\"hidden item\"/>\r\n");
      out.write("\t\t\t<input type=\"Button\" id=\"addButton\"/>\t\r\n");
      out.write("\t\t\t<hr/>\t\t\t\t\r\n");
      out.write("\t\t\t<form id=\"orderForm\">\t\t\r\n");
      out.write("\t\t\t<label for=\"totalCost\">Food Cost:</label>\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"totalCost\" class=\"total readOnly cost\"/>\t\r\n");
      out.write("\t\t\t<label for=\"finalCost\">Total Cost:</label>\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"finalCost\" class=\"total readOnly\"/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"custId\" class=\"required hidden\"/>\t\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"orderId\" class=\"hidden\"/>\t\t\t\t\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"orderInfo\" class=\"hidden\"/>\t\r\n");
      out.write("\t\t\t<label for=\"discount\">Discount:</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"discount\" class=\"onlyNumbers cost\"/>%\r\n");
      out.write("\t\t\t<label for=\"credit\">Credit: $</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"credit\" class=\"onlyDecimalNumbers cost\"/>\t\r\n");
      out.write("\t\t\t<br/>\t\t\t\r\n");
      out.write("\t\t\t<label for=\"deliveryDate\">Delivery Date:</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"deliveryDate\" class=\"readOnly\"/>\t\t\r\n");
      out.write("\t\t\t<label for=\"deliveryTime\">Delivery Time:</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"deliveryTime\" class=\"readOnly\"/>\t\t\r\n");
      out.write("\t\t\t<br/>\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"enterDeliveryZipButton\"/>\r\n");
      out.write("\t\t\t<label for=\"deliveryFee\">Delivery Fee: $</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"deliveryFee\" class=\"onlyDecimalNumbers cost\"/>\r\n");
      out.write("\t\t\t<label for=\"tollExpense\">Toll Expense: $</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"tollExpense\" class=\"onlyDecimalNumbers cost\"/>\r\n");
      out.write("\t\t\t<label for=\"changeDue\">Change Due: $</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"changeDue\" class=\"onlyDecimalNumbers cost\"/>\t\t\t\t\t\r\n");
      out.write("\t\t\t<br/>\t\t\t\t\t\r\n");
      out.write("\t\t\t<label for=\"paymentMethod\">Payment Method:</label>\r\n");
      out.write("\t\t\t<select id=\"paymentMethod\"><!-- iterate through payment methods-->\r\n");
      out.write("\t\t\t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t");

				Set<String> keys = Order.PAYMENT_METHOD.keySet(); 
				   for (String key: keys) {
			
      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(Order.PAYMENT_METHOD.get(key));
      out.write('"');
      out.write('>');
      out.print(Order.PAYMENT_METHOD.get(key));
      out.write("</option>\t\t\t\r\n");
      out.write("\t\t\t");

			   }
			
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label for=\"delivered\">Delivered?</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"delivered\"/>\t\t\t\r\n");
      out.write("\t\t\t<label for=\"personal\">Personal?</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"personal\"/>\t\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"submitButton\"/>\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"cancelButton\"/>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<br/>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</form>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"rightOrder\">\r\n");
      out.write("\t\t\t<div id=\"tableDiv\">\r\n");
      out.write("\t\t\t<table id=\"orderItems\">\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th>ID</th>\r\n");
      out.write("\t        \t   \t\t<th>Item</th>\r\n");
      out.write("\t\t    \t        <th>Quantity</th>\r\n");
      out.write("\t\t    \t        <th>Unit Price</th>\r\n");
      out.write("\t\t    \t        <th>Total Price</th>\r\n");
      out.write("\t\t\t        </tr>\r\n");
      out.write("\t\t\t</table>\t\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<!-- Dialog boxes -->\r\n");
      out.write("\t\t<div id=\"incompleteCustomerDialog\" class=\"dialog\">Please enter at least first and last name and either phone number or email address.</div>\t\t\r\n");
      out.write("\t\t<div id=\"incompletePoundQuantityDialog\" class=\"dialog\">Please fill in quantity and weight.</div>\t\t\r\n");
      out.write("\t\t<div id=\"incompleteDeliveryDialog\" class=\"dialog\">Please fill in zip.</div>\t\t\t\t\r\n");
      out.write("\t\t<div id=\"orderSubmittedDialog\" class=\"dialog\"></div>\r\n");
      out.write("\t\t<div id=\"orderSubmissionFailedDialog\" class=\"dialog\">The order submission failed, please contact the admin.</div>\r\n");
      out.write("\t\t<div id=\"orderCancelledDialog\" class=\"dialog\"></div>\r\n");
      out.write("\t\t<div id=\"orderCancellationFailedDialog\" class=\"dialog\">The order cancellation failed, please contact the admin.</div>\t\t\r\n");
      out.write("\t\t<div id=\"customerSubmissionFailedDialog\" class=\"dialog\">The customer submission failed, please contact the admin.</div>\t\t\r\n");
      out.write("\t\t<div id=\"confirmCancelDialog\" class=\"dialog\">Are you sure you want to cancel?</div>\r\n");
      out.write("\t\t<div id=\"confirmSaveDialog\" class=\"dialog\">Are you sure you want to save customer?</div>\t\r\n");
      out.write("\t\t<div id=\"confirmCancelDialog\" class=\"dialog\">Are you sure you want to cancel order?</div>\t\t\t\r\n");
      out.write("\t\t<div id=\"quantityOverrideDialog\" class=\"dialog\">Quantity ordered is more than quantity in stock.</div>\t\r\n");
      out.write("\t\t<div id=\"editPoundQuantityDialog\" class=\"dialog\">\r\n");
      out.write("\t\t\t<form id=\"exactQuantityForm\">\r\n");
      out.write("\t\t\t<label for=\"exactQuantity\">Quantity:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"exactQuantity\" class=\"required onlyNumbers\"/>\r\n");
      out.write("\t\t\t<br/>\t\r\n");
      out.write("\t\t\t<label for=\"exactWeight\">Exact Weight:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"exactWeight\" class=\"required onlyDecimalNumbers\"/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div id=\"enterDeliveryZipDialog\" class=\"dialog\">\r\n");
      out.write("\t\t\t<form id=\"enterDeliveryZipForm\">\r\n");
      out.write("\t\t\t<label for=\"deliveryZip\">Delivery Destination Zip Code:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"deliveryZip\" class=\"required onlyNumbers\"/>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t\t\t\r\n");
      out.write("\t\t<div id=\"customerDialog\" class=\"dialog\">\r\n");
      out.write("\t\t\t<form id=\"customerForm\">\r\n");
      out.write("\t\t\t<label for=\"firstName\">First Name:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"firstName\" class=\"required\"/>\r\n");
      out.write("\t\t\t<br/>\t\t\t\r\n");
      out.write("\t\t\t<label for=\"lastName\">Last Name:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"lastName\" class=\"required\"/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<label for=\"streetAddress\">Street Address:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"streetAddress\" class=\"customerAddress\"/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<label for=\"aptAddress\">Apartment/Unit Number:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"aptAddress\" class=\"customerAddress\"/>\r\n");
      out.write("\t\t\t<br/>\t\t\t\r\n");
      out.write("\t\t\t<label for=\"city\">City:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"city\" class=\"customerAddress\"/>\r\n");
      out.write("\t\t\t<label for=\"state\">State:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"state\" class=\"customerAddress\"/>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<label for=\"zip\">Zip:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"zip\" class=\"onlyNumbers customerAddress\"/>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<label for=\"phone\">Phone Number:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"phone\" class=\"onlyNumbers\"/>\r\n");
      out.write("\t\t\t<br/>\t\r\n");
      out.write("\t\t\t<label for=\"email\">Email:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"email\" class=\"email\"/>\t\t\t\t\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"editCustId\" class=\"hidden\"/>\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
